---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-conf
  namespace: openstack
  
data:
  config: |
    [global]
    fsid = c85411c7-6c67-4fc0-a9a0-999deef863d6 
    admin_secret = AQAJyRxaAmhlOxAARY4nhp5UMoHvtGXgFpQBeA== 
    cluster_name = rook 
    mon_secret = AQAJyRxa9HpqORAAfMHbP49MP4pdW05r2cU0jQ== 
    cephx =  true
    mon initial members       = rook-ceph-mon0 rook-ceph-mon1 rook-ceph-mon2 
    mon host                  = 10.233.34.193:6790,10.233.49.167:6790,10.233.36.10:6790 
    log file                  = /dev/stdout
    mon cluster log file      = /dev/stdout
    public addr               = 10.233.34.193
    cluster addr              = 10.233.102.133 
    mon keyvaluedb            = rocksdb
    mon_allow_pool_delete     = true
    debug default             = 0
    debug rados               = 0
    debug mon                 = 0
    debug osd                 = 0
    debug bluestore           = 0
    debug filestore           = 0
    debug journal             = 0
    debug leveldb             = 0
    filestore_omap_backend    = rocksdb
    osd pg bits               = 11
    osd pgp bits              = 11
    osd pool default size     = 1
    osd pool default min size = 1
    osd pool default pg num   = 100
    osd pool default pgp num  = 100
    osd objectstore           =
    rbd_default_features      = 3
    fatal signal handlers     = false 
