---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-conf
  namespace: openstack
  
data:
  config: |
    [global]
    fsid = c318acb3-7195-43ea-a9b5-cac6e9d51c1f 
    admin_secret = AQBWxBVaRempMxAAW6jMf7e9N+MpRHRkxODR0Q== 
    cluster_name = rook 
    mon_secret = AQBWxBVaZp2RMRAAaApSNe9bafODQwHQ+FE5xw== 
    cephx =  true
    mon initial members       = rook-ceph-mon0 rook-ceph-mon1 rook-ceph-mon2 
    mon host                  = 10.233.23.56:6790,10.233.15.160:6790,10.233.57.176:6790 
    log file                  = /dev/stdout
    mon cluster log file      = /dev/stdout
    public addr               = 10.233.23.56
    cluster addr              = 10.233.102.145 
    mon keyvaluedb            = rocksdb
    mon_allow_pool_delete     = true
    debug default             = 0
    debug rados               = 0
    debug mon                 = 0
    debug osd                 = 0
    debug bluestore           = 0
    debug filestore           = 0
    debug journal             = 0
    debug leveldb             = 0
    filestore_omap_backend    = rocksdb
    osd pg bits               = 11
    osd pgp bits              = 11
    osd pool default size     = 1
    osd pool default min size = 1
    osd pool default pg num   = 100
    osd pool default pgp num  = 100
    osd objectstore           =
    rbd_default_features      = 3
    fatal signal handlers     = false 
