---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-conf
  namespace: openstack
  
data:
  config: |
    [global]
    fsid = {{fsid}} 
    admin_secret = {{rook_admin_key}} 
    cluster_name = {{rook_cluster_name}} 
    mon_secret = {{rook_mon_key}} 
    cephx =  true
    mon initial members       = {{mon_names}} 
    mon host                  = {{mon_host}} 
    log file                  = /dev/stdout
    mon cluster log file      = /dev/stdout
    public addr               = {{service_address}}
    cluster addr              = {{cluster_address}} 
    mon keyvaluedb            = rocksdb
    mon_allow_pool_delete     = true
    debug default             = 0
    debug rados               = 0
    debug mon                 = 0
    debug osd                 = 0
    debug bluestore           = 0
    debug filestore           = 0
    debug journal             = 0
    debug leveldb             = 0
    filestore_omap_backend    = rocksdb
    osd pg bits               = 11
    osd pgp bits              = 11
    osd pool default size     = 1
    osd pool default min size = 1
    osd pool default pg num   = 100
    osd pool default pgp num  = 100
    osd objectstore           =
    rbd_default_features      = 3
    fatal signal handlers     = false 
